spring:
  application:
    name: demo-spring-cloud-service-admin


server:
  port: 8763

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/