spring:
  application:
    name: demo-spring-cloud-zipkin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8771

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/