spring:
  application:
    name: demo-spring-cloud-zuul

server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: demo-spring-cloud-web-admin-feign
    api-b:
      path: /api/b/**
      serviceId: demo-spring-cloud-web-admin-ribbon